name: Sync submodule updates to parent repository

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          host='github.com'
          hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
          ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts

      - uses: actions/checkout@v2
        with:
          repository: bitcointranscripts/bitcointranscripts.github.io
          token: ${{ secrets.PRIVATE_TOKEN }}

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - content update"
          git add --all
          git commit -m "content update" || echo "No changes to commit"
          git push